### ISSUE TITLE
OnNetworkChanged gives the wrong chainId

### ISSUE THREAD

**Issue by AlexandreBazeaud** [michielpost/MetaMask.Blazor#1]
Pretty self explanitory, when calling `GetSelectedChain()` and also when using `MetaMaskService.GetSelectedChain` the returned chain id is wrong, the reason is network is the chaindId already parsed to decimal
So for example when connected to BSC whom chainId is 0x38 `GetSelectedChain()` return 86
because MetaMask send the networkId which is 56 and the C# code take it as HEX and translate it to 86
Adding to this OnNetworkChanged is marked as deprecated in Metamask documentation and they are now using the even "chainChanged" and gives the chainId
I'm working on adding my pr to fix this, hope i was clear enough

**Comment by michielpost** [comment]
Published version 1.3.0 to NuGet with this fix.
