### ISSUE TITLE
Add support for Nethereum FunctionMessage-derived methods

### ISSUE THREAD

**Issue by robertmclaws** [michielpost/MetaMask.Blazor#12]
Given the following code:

```c#
[Function("deposit")]
public class DepositFunction : FunctionMessage
{
}

var deposit = new DepositFunction()
{
    FromAddress = someAddress,
    AmountToSend = Web3.Convert.ToWei(tokensRequested * AppState.CurrentSale.MintPrice)
};
```

I need to be able to call something like `MetaMaskService.SendTransaction(contractAddress, deposit);`, and have it properly construct the entire transaction (including the properties in [ContractMessageBase](https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Contracts/CQS/ContractMessageBase.cs)).

I need it to be functionally equivalent to [this](https://github.com/Nethereum/Nethereum.Metamask.Blazor/blob/master/Nethereum.Erc20.Blazor/Erc20Transfer.razor#L80-L84), without the convoluted architecture or setup hassle.

Thanks!

**Comment by michielpost** [comment]
This library does not have easy helpers yet for ERC20 transfers. It would be very useful to have these helpers. I'm not actively developing them right now, a PR is always welcome.

**Comment by robertmclaws** [comment]
Hello! This was closed as completed, is there some code I can see for the implementation?

**Comment by michielpost** [comment]
> Hello! This was closed as completed, is there some code I can see for the implementation?

Yes, I'd love to see some code for this. But there was no PR submitted yet? Are you still planning on submitting the PR? Then I will reopen.
