### ISSUE TITLE
Add `IMetaMaskService` to improve testability

### ISSUE THREAD

**Issue by Stitch-Lunar** [michielpost/MetaMask.Blazor#13]
Hey,

I would like for the `MetaMaskService` to implement an interface that defines its methods to improve testability in places that it is used.

I can supply a PR that implements this change if you approve of the change. 😊

Best regards
Stitch

**Comment by michielpost** [comment]
Yes, a PR is very much welcome. Thanks!

**Comment by Stitch-Lunar** [comment]
Awesome. I will get that out tomorrow.
