### ISSUE TITLE
_content/metaMaskJsInterop.js missing when publishing

### ISSUE THREAD

**Issue by Chris-Grundy** [michielpost/MetaMask.Blazor#17]
When an WASM Blazor app that uses the NuGet package or references the MetaMask.Blazor project is published, the app is broken due to the file _content/metaMaskJsInterop.js not being included

It can be fixed by manually deploying the file to the expected location.

This was tested by building the sample App exactly as it is in the repo as version 1.7 and it runs perfectly

Then tested again by publishing to a folder (using Visual Studio 2022 folder publishing), copying the folder to a Linux server with Nginx, and the app produces an unhandled exception during initialization

Then fixed by manually deploying the JS file

**Comment by Chris-Grundy** [comment]
Please disregard, the file is not missing. I opened this by mistake.

**Comment by michielpost** [comment]
No problem. Happy to hear it is solved.
