### ISSUE TITLE
How to receive and send tokens via different network using this repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [michielpost/MetaMask.Blazor#19]
Hello:
First, I want to know if I can receive tokens from one network, and send the tokens to another address via another network using this repo.
One example is: if I want to receive some USDT via ERC20 network, then I want to send the received USDT, less the gas fees to another address via BEP20 network.
Second, I read the documents, but I didn’t see that this wallet support Bitcoin or the tokens on Bitcoin network, let me know if the wallet supports Bitcoin and the tokens on Bitcoin network.
Finally, I don’t know how to use the repo.
Do I have to write a ASP.NET project to run this?
Or, a simple C# Console project or WinForms App project?
I am using Visual Studio 2022 (Version 17.4.2) on Windows 10 PRO (22H2).
Please advise,
Thanks,

**Comment by michielpost** [comment]
This repo focusses on Blazor WebAssembly applications running in the browser.
This library let's you communicate with the MetaMask browser plugin.

MetaMask is the actual crypto wallet, receiving and sending tokens on different networks. This library can communicate with the MetaMask JavaScript API.

More info on https://metamask.io
MetaMask does not support Bitcoin.
This library does not support swapping coins. But it can interact with MetaMask on any network MetaMask is connected to.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I didn't see any notice for your reply in my email.
As I had some experience with MetaMask before, what I can remember is each time if I want to do anything, MetaMask will ask me for permssion, therefore, a lot of click on yes button.
I just want to know if I can use your repo to login to MetaMask, afterwards, run any MetaMask API without clicking on Yes button each time?
Finally, what is  the best way to run your repo?
What I am used to is that I use Playwright to launch Chrome or Edge browser and open remote debug port, then use Playwright to control Chrome/Edge browser, I can use code to fill in like text input box, like: user name, password.
And click on som buttons on the web page via Playwright.
To use your repo, do I have to setup a ASP.NET page, and what is the next steps?
Is it possible that I use Playwright to launch Chrome/Edge browser without an ASP.NET page?
Please advice,
Thanks

**Comment by michielpost** [comment]
This repo only works with Blazor projects. You can download the repo and run the sample app.

When user permission is needed, MetaMask will prompt the user. There is no way around that.
I have no experience with Playwright and this repo is not tested with Playwright.

**Comment by zydjohnHotmail** [comment]
Thanks for your reply.
I will do some testing, but close this for now.
Thank you for your advice.
