### ISSUE TITLE
Please add retrieve balances

### ISSUE THREAD

**Issue by pomeara** [michielpost/MetaMask.Blazor#4]
Hi looks like a great starter project.

Could you please add balance/token retrieval for eth/bsc and other networks

Thanks

**Comment by michielpost** [comment]
I added an option to get your ETH balance. It's in the sample and live demo: https://2g0ch2fm4kpn1sappnldbsv1bk7nl596luouqidjrfugioec70enh3g.siasky.net/

It's in NuGet version 1.4.1

Getting other token balances isn't as straight forward as the Eth balance. Most examples use the old web3js way, but that's deprecated. So if you find an example how to do that in JavaScript, you can post it here or implement it with a PR of course :)
