### ISSUE TITLE
Reason for Disconnect Event Commented Out?

### ISSUE THREAD

**Issue by DataMarveler** [michielpost/MetaMask.Blazor#8]
I noticed in the MetaMaskService.cs file and the metaMaskInterop.js files that both the JS and C# Disconnect events are commented out. Any reason as to why? When you disconnect the wallet, the events you have listed want to reconnect, but don't clear out the user's info

**Comment by DataMarveler** [comment]
Nevermind. You can use the IsSiteConnected function to catch it before it calls the GetSelectedAddress function.

```
       async Task MetaMaskService_AccountChangedEvent(string arg)
        {
            // If the user rejected connecting the app after disconnecting
            try
            {
                // If connected then call the Get Selected Address function
                IsSiteConnected = await MetaMaskService.IsSiteConnected();

                if (IsSiteConnected)
                {
                    await GetSelectedAddress();
                }
                else
                {
                    // Clear out any user information
                    SelectedAddress = null;
                    SelectedChain = null;
                    IsSiteConnected = false;
                    Console.Clear();
                }
            }
            catch
            {
                // Clear out any user information
                SelectedAddress = null;
                SelectedChain = null;
                IsSiteConnected = false;
                Console.Clear();
            }
            StateHasChanged();
        }
```

**Comment by aeongt710** [comment]
Im using dotnet core 7, account change event never triggers

**Comment by michielpost** [comment]
I added the connect/disconnect event.

Also tested the account change. This triggers when I test it. You need to connect your site/sample app to multiple MetaMask accounts. Then in MetaMask, click the connected button and switch between one of the connected accounts
